# Complete KPI Configuration for Configurable Incremental Processing
# Version: 2.0
# Organization: PHINIA (Customizable)
# Last Updated: 2025-07-31

# Configuration metadata
metadata:
  version: "2.0"
  organization: "PHINIA"
  description: "ServiceNow ITSM KPI Configuration for Incremental Processing"
  last_updated: "2025-07-31"
  schema_version: "1.0"
  contact: "IT Service Management Team"

# Column mapping configuration - maps CSV columns to internal field names
column_mappings:
  # Core incident fields
  number: "Number"                    # Incident number/ID
  opened_at: "Created"               # Incident creation date
  resolved_at: "Resolved"            # Resolution date
  closed_at: "Closed"                # Closure date (if different from resolved)
  
  # Classification fields
  priority: "Priority"               # Priority level
  state: "Incident State"           # Current state
  category: "Category"               # Primary category
  subcategory: "Subcategory"        # Secondary category
  
  # Assignment and processing
  assignment_group: "Assignment group"     # Assigned team
  reassignment_count: "Reassignment count" # Number of reassignments
  
  # Description fields
  short_description: "Short description"   # Brief description
  description: "Description"               # Detailed description
  
  # Geographic and organizational
  country: "Country"                 # Geographic location
  location: "Location"               # Specific location
  site: "Site"                       # Site identifier
  
  # People fields (optional - may be redacted)
  caller_id: "Caller ID"            # Person who reported
  opened_by: "Opened by"            # Person who created ticket
  assigned_to: "Assigned to"        # Current assignee
  
  # Problem Management fields (for RCA and PM KPIs)
  problem:
    number: "number"
    priority: "priority"
    state: "state"
    opened_at: "opened_at"
    closed_at: "closed_at"
    resolved_at: "resolved_at"
    rca_completed: "u_rca_completed"           # Custom field - update for your org
    rca_completion_date: "u_rca_completion_date"
    rca_due_date: "u_rca_due_date"
    rca_status: "u_rca_status"
    assignment_group: "assignment_group"
    assigned_to: "assigned_to"
    short_description: "short_description"
    workaround: "workaround"
    problem_statement: "problem_statement"
    fix_notes: "fix_notes"
    related_incidents_count: "related_incidents"
    
  # Problem-Incident relationship table
  problem_incident_link:
    problem: "problem"
    incident: "incident"
    
  # Knowledge Base table (optional - for PM005)
  knowledge_base:
    number: "number"
    problem: "problem"
    short_description: "short_description"
    kb_category: "kb_category"

# Data processing configuration
processing:
  # Priority extraction settings
  priority_extraction:
    regex_pattern: "\\d+"           # Extract first number from priority text
    fallback_value: 99              # Value for unparseable priorities
    case_sensitive: false           # Case sensitivity for text matching
  
  # Date parsing configuration
  date_parsing:
    auto_detect: true              # Auto-detect date formats
    formats:                       # Supported date formats
      - "%Y-%m-%d %H:%M:%S"
      - "%Y-%m-%d"
      - "%m/%d/%Y"
    timezone: "UTC"                # Default timezone
    handle_nulls: "exclude"        # How to handle null dates
  
  # RCA-specific processing
  rca_processing:
    boolean_true_values: ["true", "True", "1", "yes", "Yes"]
    boolean_false_values: ["false", "False", "0", "no", "No"]
    rca_states_completed: ["Resolved", "Closed", "Complete"]
    rca_states_in_progress: ["Root Cause Analysis", "Assessment"]
  
  # Null handling strategy
  null_handling:
    reassignment_count: 0          # Treat null as zero
    resolved_at: "keep_null"       # Keep null for open incidents
    priority: 99                   # Default priority for nulls
  
  # Signature fields for data validation
  signature_fields:
    - "number"
    - "priority"
    - "state"
    - "reassignment_count"
    - "resolved_at"

# Threshold configuration
thresholds:
  # Priority levels
  priority:
    major_incident_levels: [1, 2]
    high_priority: 2
    medium_priority: 3
    low_priority: 4
  
  # Aging thresholds
  aging:
    backlog_days: 10               # Incident backlog threshold
    request_aging_days: 30         # Request aging threshold
    critical_aging_days: 5         # Critical attention needed
  
  # RCA thresholds
  rca:
    p1_rca_timeframe_days: 7      # P1 RCA due in 7 days
    p2_rca_timeframe_days: 14     # P2 RCA due in 14 days
    rca_completion_rate_minimum: 90.0
    rca_completion_rate_expected: 95.0
    problem_resolution_days_high_impact: 60
    problem_resolution_days_standard: 90
    repeat_incident_max_percentage: 5.0
  
  # Performance bands
  performance_bands:
    excellent: 90
    good: 80
    needs_improvement: 60
    poor: 0

# Global status determination rules
global_status_rules:
  # Overall scorecard scoring
  scorecard_scoring:
    weight_sm001: 25              # 25% weight for major incidents
    weight_sm002: 40              # 40% weight for backlog (strategic)
    weight_sm003: 25              # 25% weight for requests (if enabled)
    weight_sm004: 10              # 10% weight for first-time fix
    weight_rca001: 20             # 20% weight for RCA (if enabled)
    
    # Adjust weights if SM003 disabled
    sm003_disabled_weights:
      weight_sm001: 25            # 25% weight for major incidents  
      weight_sm002: 50            # 50% weight for backlog
      weight_sm004: 25            # 25% weight for first-time fix
    
    # Adjust weights if RCA enabled
    rca_enabled_weights:
      weight_sm001: 25
      weight_sm002: 40
      weight_sm004: 15
      weight_rca001: 20
  
  # Performance bands
  performance_bands:
    excellent: 90                 # 90-100% = Excellent
    good: 80                      # 80-89% = Good
    needs_improvement: 60         # 60-79% = Needs Improvement
    poor: 0                       # 0-59% = Poor
  
  # Escalation triggers
  escalation_triggers:
    immediate: ["p1_count > 0"]                    # Immediate escalation
    daily: ["p2_count > targets.p2_max"]          # Daily review
    weekly: ["adherence_rate < 70"]               # Weekly management review
    monthly: ["overall_score < 60"]               # Monthly executive review

# KPI definitions
kpis:
  SM001:
    name: "Major Incidents"
    enabled: true
    description: "Priority 1 & 2 Incident Processing"
    business_impact: "High"
    escalation_required: true
    calculation:
      method: "priority_count"
    targets:
      p1_max: 0
      p2_max: 5
      total_major_max: 5
    required_fields:
      - "number"
      - "priority"
    
  SM002:
    name: "ServiceNow Backlog"  
    enabled: true
    description: "Backlog Analysis"
    business_impact: "High"
    calculation:
      method: "servicenow_backlog"
    targets:
      backlog_max: 0
      adherence_min: 90.0
      aging_threshold_days: 10
    required_fields:
      - "number"
      - "opened_at"
      - "resolved_at"
    backlog_logic:
      threshold_days: 10
      include_unresolved: true
    
  SM003:
    name: "Service Request Aging"
    enabled: false
    description: "Service Request Aging Analysis"
    business_impact: "Medium"
    calculation:
      method: "request_aging"
    targets:
      aged_max: 0
      adherence_min: 90.0
    required_fields:
      - "number"
      - "opened_at"
    data_requirements:
      fallback_behavior: "disable"
    
  SM004:
    name: "First Time Fix Rate"
    enabled: true
    description: "First Time Fix Rate Analysis"
    business_impact: "High"
    calculation:
      method: "zero_reassignments"
    targets:
      ftf_rate_min: 80.0
      ftf_count_min: null
    required_fields:
      - "number"
      - "reassignment_count"
  
  # Root Cause Analysis KPI
  RCA001:
    name: "RCA Completion Rate"
    enabled: false                # Enable when problem data available
    description: "Root Cause Analysis Completion for Major Problems"
    business_impact: "Critical"
    calculation:
      method: "rca_completion"
    targets:
      rca_completion_rate_minimum: 90.0
      rca_completion_rate_expected: 95.0
      p1_rca_days: 7
      p2_rca_days: 14
    required_fields:
      - "problem.number"
      - "problem.priority"
      - "problem.rca_completed"
      - "problem.rca_completion_date"
      - "problem.rca_due_date"
    data_requirements:
      table: "problem"
      fallback_behavior: "disable"
  
  # Problem Management KPIs
  PM001:
    name: "Problem Resolution Rate"
    enabled: false
    description: "Percentage of problems resolved within target timeframe"
    business_impact: "High"
    calculation:
      method: "problem_resolution"
    targets:
      resolution_rate_min: 70.0
      high_impact_days: 60
      standard_days: 90
    required_fields:
      - "problem.number"
      - "problem.opened_at"
      - "problem.resolved_at"
      - "problem.priority"
  
  PM002:
    name: "Repeat Incident Rate"
    enabled: false
    description: "Percentage of incidents that are repeats of known problems"
    business_impact: "High"
    calculation:
      method: "repeat_incidents"
    targets:
      repeat_rate_max: 5.0
    required_fields:
      - "incident.number"
      - "problem_incident_link.problem"
      - "problem_incident_link.incident"
  
  PM003:
    name: "MTTR - Problem"
    enabled: false
    description: "Mean Time to Resolve Problems"
    business_impact: "Medium"
    calculation:
      method: "problem_mttr"
    targets:
      mttr_days_high_impact: 60
      mttr_days_standard: 90
    required_fields:
      - "problem.number"
      - "problem.opened_at"
      - "problem.resolved_at"
      - "problem.priority"
  
  PM004:
    name: "Problem-to-Incident Ratio"
    enabled: false
    description: "Number of problems per 100 incidents"
    business_impact: "Medium"
    calculation:
      method: "problem_incident_ratio"
    targets:
      ratio_min: 2
      ratio_max: 5
    required_fields:
      - "incident.number"
      - "problem.number"
  
  PM005:
    name: "KEDB Usage Rate"
    enabled: false
    description: "Percentage of incidents resolved using Knowledge Base"
    business_impact: "Medium"
    calculation:
      method: "kedb_usage"
    targets:
      usage_rate_min: 15.0
    required_fields:
      - "incident.number"
      - "knowledge_base.number"
    data_requirements:
      table: "knowledge_base"
      fallback_behavior: "disable"
    
  GEOGRAPHIC:
    name: "Geographic Analysis"
    enabled: true
    description: "Geographic Distribution Analysis"
    business_impact: "Low"
    calculation:
      method: "country_distribution"
      top_countries_limit: 5
      include_priority_breakdown: true
    analysis_dimensions:
      - "country_distribution"
      - "priority_by_country"
      - "volume_trends_by_country"
      - "kpi_performance_by_country"
    required_fields:
      - "country"
      - "priority"
      - "opened_at"
    escalation_required: false

# Output and reporting configuration
output:
  # Format settings
  formatting:
    decimal_places: 1             # Decimal places for percentages
    date_format: "YYYY-MM-DD"     # Date format for output
    include_timestamps: true      # Include processing timestamps
    include_metadata: true        # Include configuration metadata
  
  # Report sections
  report_sections:
    executive_summary: true       # High-level summary
    kpi_details: true            # Detailed KPI breakdown
    trends_analysis: false       # Trend analysis (requires historical data)
    geographic_analysis: true    # Geographic breakdown
    recommendations: true        # Improvement recommendations
    problem_management_dashboard: false  # PM dashboard (requires problem data)
    rca_compliance_report: false        # RCA compliance (requires problem data)
  
  # Alert and notification settings
  notifications:
    enabled: false               # Enable notifications
    channels: ["email"]          # Notification channels
    escalation_matrix:           # Who gets notified for what
      p1_incidents: ["manager", "director"]
      target_misses: ["team_lead"]
      weekly_summary: ["stakeholders"]

# Validation rules for configuration integrity
validation:
  # Required sections
  required_sections:
    - "metadata"
    - "column_mappings" 
    - "kpis"
    - "thresholds"
  
  # Field validation rules
  field_validation:
    targets:
      type: "numeric"
      min_value: 0
      max_value: 100
    
    thresholds:
      type: "numeric"
      min_value: 1
      max_value: 365
    
    weights:
      type: "numeric"
      min_value: 0
      max_value: 100
      sum_constraint: 100         # All weights must sum to 100
  
  # Business logic validation
  business_rules:
    - "targets.p1_max should be 0 for zero-tolerance policy"
    - "thresholds.aging.backlog_days should be <= 30 for reasonable aging"
    - "All enabled KPIs must have required_fields available in column_mappings"
    - "KPI weights must sum to 100 when all KPIs are enabled"

# Environment-specific overrides (optional)
environments:
  development:
    thresholds:
      aging:
        backlog_days: 5           # Shorter threshold for dev/testing
    
  production:
    validation:
      strict_mode: true           # Strict validation in production
    
  testing:
    kpis:
      SM001:
        targets:
          p2_max: 10              # Higher threshold for testing