# ==========================================
# OKR R002 Configuration
# File: okr_config.yaml
# Purpose: OKR R002 (Service Delivery Excellence) specifications
# Owner: All SDMs (Service Delivery Managers)
# Version: 1.0
# Last Updated: 2025-10-17
# ==========================================

metadata:
  version: "1.0"
  okr_id: "R002"
  okr_name: "Service Delivery Excellence"
  owner: "All SDMs"
  year: 2025
  last_updated: "2025-10-17"
  schema_version: "1.0"
  description: "OKR for establishing proactive service delivery with measurable outcomes"

# ==========================================
# OKR OBJECTIVE
# ==========================================
objective:
  description: "Establish a proactive service delivery model that improves operational visibility, strengthens BRM collaboration, and delivers measurable site-level outcomes"
  alignment:
    - "Global Strategic IT Objectives"
    - "BRM Collaboration"
    - "Site-Level Service Excellence"
    - "Business Value Delivery"

# ==========================================
# KEY RESULTS
# ==========================================
key_results:
  
  # KR3: MAJOR INCIDENTS MANAGEMENT
  KR3:
    name: "Major Incidents Management"
    description: "Minimize high-priority incidents (P1 and P2) to ensure service stability"
    
    # Links to KPI SM001
    calculation_source:
      kpi_id: "SM001"
      kpi_config_file: "kpi_config.yaml"
      note: "KR3 tracks SM001 - Major incidents (P1 and P2 counts)"
    
    # Business target
    target:
      value: 5.0
      unit: "count"
      operator: "<="
      description: "≤5 major incidents (P2) total, P1=0"
      p1_target: 0
      p2_target: 5
    
    # Deadline and urgency
    deadline:
      date: "2025-12-31"
      criticality: "Critical"
      priority: "Immediate"
    
    # Scoring configuration (0-100 scale)
    scoring:
      method: "inverse_count"
      formula: "100 - (current_count / max_acceptable * 100)"
      note: "Lower incident count is better, clamped scoring"
      clamp_min: 0
      clamp_max: 100
      max_acceptable: 20  # Anything above 20 major incidents = 0 score
      
      performance_bands:
        excellent:
          min_score: 90
          condition: "≤5 major incidents"
          description: "Outstanding stability"
        
        good:
          min_score: 70
          condition: "6-10 major incidents"
          description: "Good stability"
        
        at_risk:
          min_score: 40
          condition: "11-15 major incidents"
          description: "Stability concerns"
        
        critical:
          min_score: 0
          condition: ">15 major incidents"
          description: "Severe stability issues"
    
    owner: "All SDMs"
    business_impact: "Critical"
  
  # KR4: INCIDENT BACKLOG MANAGEMENT
  KR4:
    name: "Incident Backlog Management"
    description: "Ensure fewer than 10% of incidents remain open for more than 10 days"
    
    # Links to KPI SM002
    calculation_source:
      kpi_id: "SM002"
      kpi_config_file: "kpi_config.yaml"
      note: "KR4 and SM002 are the same metric - incident backlog percentage"
    
    # Business target
    target:
      value: 10.0
      unit: "percent"
      operator: "<="
      description: "≤10% of incidents aged >10 days"
    
    # Deadline and urgency
    deadline:
      date: "2025-09-30"
      criticality: "Critical"
      priority: "Immediate"
    
    # Scoring configuration (0-100 scale)
    scoring:
      method: "inverse_percentage"
      formula: "100 - (current_value / target_value * 100)"
      note: "Lower backlog is better, so inverse scoring"
      clamp_min: 0
      clamp_max: 100
      
      performance_bands:
        excellent:
          min_score: 90
          condition: "≤5% backlog"
          description: "Outstanding performance"
        
        good:
          min_score: 70
          condition: "5-10% backlog"
          description: "Meeting expectations"
        
        at_risk:
          min_score: 40
          condition: "10-15% backlog"
          description: "Requires attention"
        
        critical:
          min_score: 0
          condition: ">15% backlog"
          description: "Immediate intervention required"
    
    owner: "All SDMs"
    business_impact: "High"
  
  # KR5: REQUEST BACKLOG MANAGEMENT
  KR5:
    name: "Request Backlog Management"
    description: "Ensure fewer than 30% of service requests aged beyond 30 days"
    
    # Links to KPI SM003
    calculation_source:
      kpi_id: "SM003"
      kpi_config_file: "kpi_config.yaml"
      note: "KR5 uses SM003 - request aging with 30-day threshold"
    
    # Business target
    target:
      value: 30.0
      unit: "percent"
      operator: "<="
      description: "≤30% of requests aged >30 days"
    
    # Deadline and urgency
    deadline:
      date: "2025-12-31"
      criticality: "High"
      priority: "Standard"
    
    # Scoring configuration (0-100 scale)
    scoring:
      method: "inverse_percentage"
      formula: "100 - (current_value / target_value * 100)"
      note: "Lower backlog is better, so inverse scoring"
      clamp_min: 0
      clamp_max: 100
      
      performance_bands:
        excellent:
          min_score: 90
          condition: "≤15% aged requests"
          description: "Outstanding performance (50% better than target)"
        
        good:
          min_score: 70
          condition: "15-30% aged requests"
          description: "Meeting expectations (at or near target)"
        
        at_risk:
          min_score: 40
          condition: "30-45% aged requests"
          description: "Requires attention (above target)"
        
        critical:
          min_score: 0
          condition: ">45% aged requests"
          description: "Immediate intervention required (50% over target)"
    
    owner: "Service Request Team"
    business_impact: "Medium"
  
  # KR6: FIRST TIME FIX RATE
  KR6:
    name: "First Time Fix Rate"
    description: "Achieve ≥80% first-time fix rate using ServiceNow FCR standard"
    
    # Links to KPI SM004
    calculation_source:
      kpi_id: "SM004"
      kpi_config_file: "kpi_config.yaml"
      note: "KR6 and SM004 are the same metric - first time fix rate"
    
    # Business target
    target:
      value: 80.0
      unit: "percent"
      operator: ">="
      description: "≥80% first-time fix"
    
    # Deadline and urgency
    deadline:
      date: "2025-12-31"
      criticality: "High"
      priority: "Standard"
    
    # Scoring configuration (0-100 scale)
    scoring:
      method: "direct_percentage"
      formula: "(current_value / target_value) * 100"
      note: "Higher fix rate is better, so direct scoring"
      clamp_min: 0
      clamp_max: 100
      
      performance_bands:
        excellent:
          min_score: 90
          condition: "≥72% FTF (90% of target)"
          description: "Outstanding quality"
        
        good:
          min_score: 70
          condition: "64-72% FTF (70-90% of target)"
          description: "Good quality"
        
        at_risk:
          min_score: 40
          condition: "48-64% FTF (40-70% of target)"
          description: "Quality concerns"
        
        critical:
          min_score: 0
          condition: "<48% FTF (<40% of target)"
          description: "Significant quality issues"
    
    owner: "Service Desk Management"
    business_impact: "High"

# ==========================================
# OKR WEIGHTING & SCORING
# ==========================================
weighting:
  description: "Weighted scoring across four Key Results"
  total_weight: 100
  
  rationale:
    KR3: "20% - Major incidents (P1/P2) - Service stability"
    KR4: "35% - Incident Backlog - Process efficiency"
    KR5: "25% - Request Backlog - Service responsiveness"
    KR6: "20% - First Time Fix - Quality indicator"
  
  weights:
    KR3: 20    # Major Incidents - Service stability
    KR4: 35    # Incident Backlog - Process efficiency
    KR5: 25    # Request Backlog - Service responsiveness
    KR6: 20    # First Time Fix - Quality metric
  
  overall_score:
    formula: "(KR3_score × 0.20) + (KR4_score × 0.35) + (KR5_score × 0.25) + (KR6_score × 0.20)"
    rounding: 1
    min_score: 0
    max_score: 100
    
    performance_bands:
      excellent:
        min_score: 90
        max_score: 100
        status: "🟢 EXCELLENT"
        description: "All Key Results on track or exceeded"
      
      on_track:
        min_score: 70
        max_score: 89
        status: "🟡 ON TRACK"
        description: "Most Key Results progressing well"
      
      at_risk:
        min_score: 50
        max_score: 69
        status: "🟠 AT RISK"
        description: "Multiple Key Results need attention"
      
      critical:
        min_score: 0
        max_score: 49
        status: "🔴 CRITICAL"
        description: "Significant intervention required"

# ==========================================
# GEOGRAPHIC ANALYSIS
# ==========================================
geographic_analysis:
  enabled: true
  description: "Identify location-specific performance issues and best practices"
  
  dimensions:
    - "country"
    - "location"
  
  metrics_to_analyze:
    - kr_id: "KR4"
      group_by: ["country", "location"]
      metrics: ["backlog_percentage", "backlog_count"]
    
    - kr_id: "KR5"
      group_by: ["country", "location"]
      metrics: ["aged_percentage", "aged_count"]
    
    - kr_id: "KR6"
      group_by: ["country", "location"]
      metrics: ["ftf_rate", "ftf_count"]
  
  volume_tiers:
    tier_1:
      name: "High Volume"
      threshold: 500
      description: "≥500 incidents/requests per quarter"
      characteristics: "Major hubs requiring dedicated resources"
    
    tier_2:
      name: "Medium Volume"
      threshold: 200
      description: "200-499 incidents/requests per quarter"
      characteristics: "Standard sites with regular support"
    
    tier_3:
      name: "Standard Volume"
      threshold: 100
      description: "100-199 incidents/requests per quarter"
      characteristics: "Smaller sites with basic coverage"
    
    tier_4:
      name: "Low Volume"
      threshold: 0
      description: "<100 incidents/requests per quarter"
      characteristics: "Remote or small sites"
  
  intervention_priority:
    critical:
      criteria: "High volume AND poor performance"
      action: "Immediate attention required"
      example: "Tier 1 site with backlog >20%"
    
    high:
      criteria: "High volume OR poor performance"
      action: "Scheduled intervention within 2 weeks"
      example: "Tier 2 site with FCR <60%"
    
    monitor:
      criteria: "Low volume with poor performance"
      action: "Close monitoring, quarterly review"
      example: "Tier 4 site with backlog >15%"
    
    standard:
      criteria: "Meeting all targets"
      action: "Continue standard operations"
      example: "Any tier meeting KR targets"

# ==========================================
# ACTION TRIGGERS
# ==========================================
action_triggers:
  description: "Automatic action recommendations based on performance"
  
  KR3:
    critical:
      condition: "total_major > 15 OR p1_count > 0"
      action: "Immediate incident review and root cause analysis"
      escalation: "IT Leadership"
      frequency: "Immediate"
    
    warning:
      condition: "total_major > 5"
      action: "Weekly major incident review meeting"
      escalation: "SDM Team"
      frequency: "Weekly"
  
  KR4:
    critical:
      condition: "deadline < 7 days AND backlog > 15%"
      action: "Emergency backlog clearance mode"
      escalation: "IT Leadership"
      frequency: "Immediate"
    
    warning:
      condition: "backlog > 10%"
      action: "Daily monitoring and reporting"
      escalation: "SDM Team"
      frequency: "Daily"
  
  KR5:
    warning:
      condition: "aged_percentage > 30%"
      action: "Weekly backlog review meeting"
      escalation: "Service Request Team"
      frequency: "Weekly"
  
  KR6:
    critical:
      condition: "ftf_rate < 50%"
      action: "Comprehensive training program required"
      escalation: "Service Desk Management"
      frequency: "Immediate"
    
    warning:
      condition: "ftf_rate < 70%"
      action: "Review assignment rules and knowledge base"
      escalation: "Team Leads"
      frequency: "Bi-weekly"

# ==========================================
# REPORTING CONFIGURATION
# ==========================================
reporting:
  frequencies:
    daily:
      enabled: true
      scope: ["KR4"]
      note: "KR4 only until Sept 30 deadline"
      recipients:
        - "SDM Team"
        - "IT Leadership"
    
    weekly:
      enabled: true
      scope: ["KR4", "KR5", "KR6"]
      recipients:
        - "SDM Team"
        - "Service Desk Management"
        - "IT Leadership"
    
    biweekly:
      enabled: true
      scope: ["KR5"]
      note: "Focus on request backlog"
      recipients:
        - "Service Request Team"
        - "SDM Team"
    
    monthly:
      enabled: true
      scope: ["Geographic Analysis"]
      recipients:
        - "SDM Team"
        - "BRMs"
        - "IT Leadership"
    
    quarterly:
      enabled: true
      scope: ["Complete OKR Assessment"]
      recipients:
        - "Infrastructure Team"
        - "IT Leadership"
        - "Executive Team"
  
  excel_output:
    sheets:
      okr_summary:
        enabled: true
        name: "OKR R002 Summary"
        include:
          - "Overall OKR Score"
          - "Individual KR Scores"
          - "Status & Targets"
          - "Days Remaining to Deadlines"
          - "Weights & Calculation"
      
      kr_details:
        enabled: true
        name: "Key Results Detail"
        include:
          - "KR4 - Incident Backlog Details"
          - "KR5 - Request Backlog Details"
          - "KR6 - First Time Fix Details"
          - "Current vs Target Analysis"
          - "Gap Analysis"
          - "Trend Data (if available)"
      
      geographic_okr:
        enabled: true
        name: "OKR by Geography"
        include:
          - "Country-level OKR scores"
          - "Location-level OKR scores"
          - "Volume tiers by geography"
          - "Performance ranking"
      
      action_items:
        enabled: true
        name: "Action Items"
        include:
          - "Triggered actions (critical & warning)"
          - "KRs missing target"
          - "Recommended interventions"
          - "Priority rankings"
          - "Owner assignments"

# ==========================================
# VALIDATION RULES
# ==========================================
validation:
  required_kpis:
    - "SM001"    # For KR3
    - "SM002"    # For KR4
    - "SM003"    # For KR5
    - "SM004"    # For KR6
  
  weight_validation:
    sum_must_equal: 100
    all_weights_positive: true
    min_weight: 10
    max_weight: 60
  
  target_validation:
    all_targets_numeric: true
    all_deadlines_valid: true
    deadlines_in_future: false    # Allow past deadlines for tracking
  
  kpi_result_requirements:
    SM001:
      required_fields:
        - "p1_count"
        - "p2_count"
        - "total_major"
    
    SM002:
      required_fields:
        - "backlog_percentage"
        - "backlog_count"
        - "total_count"
    
    SM003:
      required_fields:
        - "aged_percentage"
        - "aged_count"
        - "total_count"
    
    SM004:
      required_fields:
        - "ftf_rate"
        - "ftf_count"
        - "eligible_count"

# ==========================================
# NOTES & REFERENCES
# ==========================================
notes:
  calculation_references:
    - "See kpi_config.yaml for detailed KPI calculation methods"
    - "See complete_kpi_config.yaml for comprehensive documentation"
  
  version_history:
    v1_0:
      date: "2025-10-17"
      changes:
        - "Initial OKR config structure"
        - "Defined KR4, KR5, KR6 specifications"
        - "Established weighting and scoring logic"
        - "Added geographic analysis framework"
  
  key_differences_from_kpi_config:
    - "OKR config focuses on business objectives and deadlines"
    - "KPI config focuses on technical calculation methods"
    - "OKR config defines weighted scoring across KRs"
    - "KPI config defines individual metric calculations"
  
  usage:
    - "Load with okr_calculator.py"
    - "Requires KPI results as input"
    - "Produces weighted OKR scores (0-100)"
    - "Generates action triggers and recommendations"
